Resolve old flags preventing lisk_snapshot.sh execution - Closes #205
LiskHQ/lisk-build pull request #206
Opened 2017-10-17 15:03 UTC by Isabello

Closes #205

2017-10-17 15:10 UTC, ghost requested changes

2017-10-17 15:10 UTC, fchavant commented on scripts/lisk_snapshot.sh
> +    bash lisk.sh stop_node -p "$SNAPSHOT_CONFIG"
Should that not be `"$PM2_CONFIG"`?

2017-10-17 15:22 UTC, MaciejBaj approved these changes
:)

2017-10-17 15:30 UTC, Isabello commented on scripts/lisk_snapshot.sh
> +    bash lisk.sh stop_node -p "$SNAPSHOT_CONFIG"
fixed

2017-10-18 06:30 UTC, ghost approved these changes

2017-10-18 13:24 UTC, merged