Gr33n's update take2
LiskHQ/lisk-build pull request #73
Opened 2017-02-15 04:18 UTC by Gr33nDrag0n69

### lisk_snapshot.sh changelog

- Change value of failed snapshot in progress from 24 hours to 30 minutes.
- Added dropdb on target database before exit
- Added missing test in waiting loop for stalled/failure detection
- Added -v switch ( forced full vacuum ) to eliminate the need for lot of freespace during process.
- Added -m params to allow custom delay between vacuum. (Instead of default 5 minutes)
- Added spacing in usage menu
- Modified end of script cleanup section.
- Move stall values to minutes and defined as variables
- Added date to start of each output line.

2017-02-15 05:01 UTC, Gr33nDrag0n69 commented
Now that basic script is updated, I entered troubleshooting the last implematation for reccuring execution each 3 minutes for better cronjob efficiency. Using the PID as a lock file (like initialy proposed) work only in command line. When it`'s run as cronjob the test never detect the already ruunning instance. I will remove the PID test and replace it by a lock file during the week. The 2nd advantage of a lock file is the fact that it can be set at start and remove at the end without the possibility of a period of time the script is running but not the node instance.

2017-02-15 08:19 UTC, Isabello requested changes
Remove the flag for checking if vacuum is enabled or not. we will deploy vacuuming universally for all systems.

2017-02-15 08:19 UTC, Isabello commented on scripts/lisk_snapshot.sh
> +  if [ "$PGSQL_VACUUM" == "Y" ] 2> /dev/null; then
We dont need the flag, we should just force vacuuming mem_rounds on all deployments for consistency purposes. Adding this complexity creates more troubleshooting hurdles that are unneccessary

2017-02-15 08:19 UTC, Isabello commented on scripts/lisk_snapshot.sh
> +echo -e "\n$( date +'%Y-%m-%d %H:%M:%S' ) Snapshot verification process completed"
Please turn this date command into a callable function to improve readability

2017-02-15 08:19 UTC, Isabello commented on scripts/lisk_snapshot.sh
> +  echo -e "\nUsage: $0 [-t <snapshot.json>] [-s <config.json>] [-b <backup directory>] [-d <days to keep>] [-r <round>] [-g] [-v] [-m <vacuum delay>]\n"
Remove this flag and just set vaccuum to always on using a hardcoded cycle of 15-30 minutes or so.

2017-02-15 10:13 UTC, Gr33nDrag0n69 commented on scripts/lisk_snapshot.sh
> +  echo -e "\nUsage: $0 [-t <snapshot.json>] [-s <config.json>] [-b <backup directory>] [-d <days to keep>] [-r <round>] [-g] [-v] [-m <vacuum delay>]\n"
No

2017-02-15 10:13 UTC, Gr33nDrag0n69 commented on scripts/lisk_snapshot.sh
> +  if [ "$PGSQL_VACUUM" == "Y" ] 2> /dev/null; then
No

2017-02-15 10:14 UTC, Gr33nDrag0n69 commented on scripts/lisk_snapshot.sh
> +echo -e "\n$( date +'%Y-%m-%d %H:%M:%S' ) Snapshot verification process completed"
You say jump I say how high ? Probably later, not affecting functionnality in any way.

2017-02-15 10:40 UTC, Gr33nDrag0n69 commented on scripts/lisk_snapshot.sh
> +  echo -e "\nUsage: $0 [-t <snapshot.json>] [-s <config.json>] [-b <backup directory>] [-d <days to keep>] [-r <round>] [-g] [-v] [-m <vacuum delay>]\n"
-v is ok to remove but -m will stay with default value 5

2017-02-15 10:41 UTC, Gr33nDrag0n69 commented on scripts/lisk_snapshot.sh
> +  if [ "$PGSQL_VACUUM" == "Y" ] 2> /dev/null; then
hurdles, lol. Using PID in a sub-directory for lock functionnality is hurdle for troubleshooting. But yes, I'll remove the -v switch

2017-02-15 10:46 UTC, Gr33nDrag0n69 commented on scripts/lisk_snapshot.sh
> +echo -e "\n$( date +'%Y-%m-%d %H:%M:%S' ) Snapshot verification process completed"
Aceept the pull request and modify it later if it's so important to you. I won.'t modify.

2017-02-15 10:49 UTC, Gr33nDrag0n69 commented on scripts/lisk_snapshot.sh
> +  if [ "$PGSQL_VACUUM" == "Y" ] 2> /dev/null; then
And by the way, the switch is there tp allow poeple to skip the functionnality. Can I remember you that you said yourself in the chat when I proposed this modification: No, I don't have the problem myself so I don't need this functionnaility.

2017-02-15 10:53 UTC, Isabello commented on scripts/lisk_snapshot.sh
> +  echo -e "\nUsage: $0 [-t <snapshot.json>] [-s <config.json>] [-b <backup directory>] [-d <days to keep>] [-r <round>] [-g] [-v] [-m <vacuum delay>]\n"
We do not need a flag to adjust it, we can establish standards for all systems instead.

2017-02-15 10:55 UTC, Isabello commented on scripts/lisk_snapshot.sh
> +echo -e "\n$( date +'%Y-%m-%d %H:%M:%S' ) Snapshot verification process completed"
im asking you to modify it to meet our standards, this is the purpose of a code review process.

2017-02-15 10:56 UTC, Gr33nDrag0n69 commented
Removed -v
Changelog updated

2017-02-15 22:27 UTC, Gr33nDrag0n69 commented
Attacking lock file implementation and initial testing tonight

2017-02-15 23:41 UTC, Gr33nDrag0n69 commented
I just understood why there is so much double quotes in the script

2017-02-15 23:42 UTC, Gr33nDrag0n69 commented
early testing working great so far, will report back tommorow for final confirmation

2017-02-16 04:40 UTC, Gr33nDrag0n69 commented
everything is working fine. (3 auto-snap using lock file without bug) no more commit planned on this pull request.

2017-02-16 08:01 UTC, Isabello approved these changes

2017-02-16 08:01 UTC, Isabello commented on scripts/lisk_snapshot.sh
> +now() {
Thank you for this.

2017-02-16 08:01 UTC, merged